import type { Metadata } from 'next';
import { Poppins, Open_Sans } from 'next/font/google';
import localFont from 'next/font/local'; 
import './globals.css';
//import '@rainbow-me/rainbowkit/styles.css';
//import { ThemeProvider } from '@/components/theme-provider'
//import { Providers } from './providers'; 
//import { NextProviders } from './next-providers'

const poppins = Poppins({ 
    subsets: ['latin'], 
    variable: '--font-poppins',
    weight: ['400', '500', '600'] 
});
const openSans = Open_Sans({ 
    subsets: ['latin'],
    variable: '--font-open',
    weight: '700' 
}); 
const bukaBird = localFont({
    src: '../public/Buka Bird.ttf',
    variable: '--font-bb',
    display: 'swap',
}); 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} ${openSans.variable} ${bukaBird.variable}`}>{children}</body>
    </html>
  );
}
